stages:
  - build

before_script:
  - virtualenv -p python3 env
  - . env/bin/activate
  - pip install twine

build_amd64_release:
  stage: build
  only:
    - tags
  script:
    - sed -i s/0.0.0-latest/$CI_COMMIT_TAG/g ./setup
    - sed -i s/0.0.0-latest/$CI_COMMIT_TAG/g ./vathos/__init__.py
    - ./setup clean
    - ./setup sdist bdist_wheel --plat-name manylinux1_x86_64
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --verbose --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*.whl
  artifacts:
    expire_in: never
    paths:
      - "dist/*.whl"
