#!/usr/bin/env python3
# -*- coding: utf-8 -*-
###############################################################################
#
# Copyright (c) 2018, Vathos GmbH
#
# All rights reserved.
#
###############################################################################

import os
from pathlib import Path

from setuptools import setup, Command, find_packages

VERSION = '0.0.0-latest'

this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()


class CleanCommand(Command):
  """
  Custom clean command to tidy up the project root.
  """
  user_options = []

  def initialize_options(self):
    pass

  def finalize_options(self):
    pass

  def run(self):
    os.system('rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info')


setup(name='vathos',
      version=VERSION,
      description='Vathos Python API.',
      author='Jonathan Balzer',
      author_email='jonathan.balzer@vathos.net',
      url='https://github.com/vathos/python.vathos.net',
      packages=find_packages(),
      install_requires=['requests>=2.27.0', 'numpy>=1.22.0', 'imageio>=2.14.0'],
      extras_require={'visualization': ['pyqt5', 'mayavi', 'trimesh']},
      scripts=[],
      include_package_data=True,
      long_description=long_description,
      long_description_content_type='text/markdown',
      cmdclass={'clean': CleanCommand})
