#!/usr/bin/env python3
# -*- coding: utf-8 -*-
###############################################################################
#
# Copyright (c) 2018, Vathos GmbH
#
# All rights reserved.
#
###############################################################################

import os

from setuptools import setup, Command, find_packages

VERSION = '0.0.0-latest'


class CleanCommand(Command):
  """
  Custom clean command to tidy up the project root.
  """
  user_options = []

  def initialize_options(self):
    pass

  def finalize_options(self):
    pass

  def run(self):
    os.system('rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info')


setup(name='vathos',
      version=VERSION,
      description='Vathos Python API.',
      author='Jonathan Balzer',
      author_email='jonathan.balzer@vathos.net',
      url='https://www.vathos-robotics.com',
      packages=find_packages(),
      install_requires=['requests'],
      scripts=[],
      include_package_data=True,
      cmdclass={'clean': CleanCommand})
